name: biblioteca

services:
  application:
    build:
      dockerfile: docker/application/Dockerfile
  db:
    build:
      context: docker/database

    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: biblioteca

    ports:
      - 5432:5432

    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - main

  panel:
    image: adminer
    ports:
      - 9000:8080
    depends_on:
      - db
    networks:
      - main

volumes:
  data:

networks:
  main:
